export const FETCH_PICTURES = 'FETCH_PICTURES';
export const FETCH_PICTURES_PENDING = 'FETCH_PICTURES_PENDING';
export const FETCH_PICTURES_FULFILLED = 'FETCH_PICTURES_FULFILLED';
export const FETCH_PICTURES_REJECTED = 'FETCH_PICTURES_REJECTED';
